### ISSUE TITLE
Recognition of changed lines seems to not work correclty

### ISSUE THREAD

**Issue by stoesselt** [jenkinsci/violation-comments-to-stash-plugin#60] opened 2018-09-26 11:33 UTC
Hi,

it seems that changed/unchanged files are recognized correctly, but changed/unchanged lines not. In the following there is an example. Line 39 of ListView.cpp changed. In this change many files have been renamed/moved. In Bitbucket Diff-View files are shown as deleted and added, but in git history, files are shown as renamed. However ListView.cpp was only modified. 

Actually, for this PR not 1 comment has been created on Bitbucket. I have retested another PR, there warnings have been recreated (after deleting them before re-execution). I encountered the problem with plug-in version 1.80. I updated to 1.89, but same problem.

![unrecognized warning](https://user-images.githubusercontent.com/38289313/46074403-c4205880-c187-11e8-9e84-4b6daaa5e283.jpg)

Compiler output, where the path is changed by script afterwards.
```
../../source/gui/controls/ListView.cpp:39:61: warning: default argument given for parameter 2 of 'pfm::ListView::ListView(const PegRect&, PEGUINT)' [-fpermissive]
```

Actually, the specific line is changed, but warning is not reported. In the plugin output you can see, that +-10 lines around changed lines should be reported:
```
Using proxy: 127.0.0.1:3128
---
--- Jenkins Violation Comments to Bitbucket Server ---
---
bitbucketServerUrl: <server-url>
projectKey: P2
repoSlug: code
pullRequestId: 48
credentialsId: true
createSingleFileComments: true
createSingleFileCommentsTasks: false
createCommentWithAllSingleFileComments: false
commentOnlyChangedContent: true
commentOnlyChangedContentContext: 10
minSeverity: INFO
keepOldComments: false
commentTemplate: 
CPPCHECK with pattern .*DeduplicatedCppcheckResult\.txt$
 with pattern .*cpplintResult\.xml$
GCC with pattern .*DeduplicatedGccOutput\.txt$
DOXYGEN with pattern .*DoxygenOutput\.txt$
Pull request: 48
Workspace: /srv/www/jenkins/workspace/code_PR-48-KGAD5IYWWUHLZ57VV6B6ZBCWRPMR3YBWCP6PDMVT4TV3MZE2KESQ
Found 131 violations from ViolationConfig [pattern=.*DeduplicatedCppcheckResult\.txt$, reporter=CPPCHECK, parser=CLANG].
Found 1089 violations from ViolationConfig [pattern=.*cpplintResult\.xml$, reporter=, parser=CPPLINT].
Found 200 violations from ViolationConfig [pattern=.*DeduplicatedGccOutput\.txt$, reporter=GCC, parser=CLANG].
Found 73 violations from ViolationConfig [pattern=.*DoxygenOutput\.txt$, reporter=DOXYGEN, parser=CLANG].
PR: P2/code/48 on <server-url>
INFO GET <server-url>rest/api/1.0/projects/P2/repos/code/pull-requests/48/changes?limit=999999 200 
INFO Files changed:
  pump/source/gui/controls/ListView.cpp
  // many other files
INFO Files with violations:
  * // this looks strange
  pump/source/gui/controls/ListView.cpp
  // many other files
INFO GET <server-url>rest/api/1.0/projects/P2/repos/code/pull-requests/48/diff?limit=999999 200 
INFO Will not include violations on changed files because violation reported on untouched lines:
  pump/source/gui/controls/ListView.cpp 18
  pump/source/gui/controls/ListView.cpp 19
  pump/source/gui/controls/ListView.cpp 199
  pump/source/gui/controls/ListView.cpp 20
  pump/source/gui/controls/ListView.cpp 21
  pump/source/gui/controls/ListView.cpp 215
  pump/source/gui/controls/ListView.cpp 22
  pump/source/gui/controls/ListView.cpp 220
  pump/source/gui/controls/ListView.cpp 27
  pump/source/gui/controls/ListView.cpp 28
  pump/source/gui/controls/ListView.cpp 281
  pump/source/gui/controls/ListView.cpp 29
  pump/source/gui/controls/ListView.cpp 30
  pump/source/gui/controls/ListView.cpp 39 // <---------------------- why untouched?
  // many other findings listed
INFO Will not include violations on unchanged files:
  * 0  // I don't know what this should mean, file names *? May this cause problems?
  /pump/external/specific/arm/cmsis/arm_math.h 2212
  // several other files, chosen files look correct
  tests/src/util/FlaggedTypeTests.cpp 268
INFO GET <server-url>rest/api/1.0/projects/P2/repos/code/pull-requests/48/changes?limit=999999 200 
INFO GET <server-url>rest/api/1.0/projects/P2/repos/code/pull-requests/48/comments?path=pump%2Fbuild%2FMakefile.common.gcc.mk&limit=999999 200 
INFO Found no comments from <server-url>rest/api/1.0/projects/P2/repos/code/pull-requests/48/comments?path=pump%2Fbuild%2FMakefile.common.gcc.mk&limit=999999 with JSONPath $.values[*] in JSON:
{"size":0,"limit":999999,"isLastPage":true,"values":[],"start":0}

// many more requests with same results but different paths

INFO Asking BitbucketServerCommentsProvider to comment:
// ends here, no comments in Bitbucket
```

**Comment by tomasbjerre** [comment] 2018-09-26 11:43
Looks like: https://github.com/tomasbjerre/violations-lib/issues/40

Can you get rid of the relative paths?

**Comment by stoesselt** [comment] 2018-09-26 11:49
So the relative path of the compiler warning is transformed properly, by script in Jenkinsfile before the plugin parses it.

Do you mean the relative path from  pump/and-so-on ? This is toplevel folder from repository, so I think this is correct.

**Comment by tomasbjerre** [comment] 2018-09-26 11:51
Try to make this:
```
../../source/gui/controls/ListView.cpp:39:61: warning: default argument given for parameter 2 of 'pfm::ListView::ListView(const PegRect&, PEGUINT)' [-fpermissive]
```
Change to:
```
pump/source/gui/controls/ListView.cpp:39:61: warning: default argument given for parameter 2 of 'pfm::ListView::ListView(const PegRect&, PEGUINT)' [-fpermissive]
```

**Comment by stoesselt** [comment] 2018-09-26 11:52
Yes, I do so, as written in both previous posts...

**Comment by tomasbjerre** [comment] 2018-09-26 12:05
Ok! I think it is something happening in this method: https://github.com/tomasbjerre/violation-comments-to-bitbucket-server-lib/blob/master/src/main/java/se/bjurr/violations/comments/bitbucketserver/lib/BitbucketServerCommentsProvider.java#L157
Returning `false` when it should return `true` in this case.

I guess you don't want to post the result of `rest/api/1.0/projects/P2/repos/code/pull-requests/48/diff?limit=999999` here? But if you email it to me, I can try to reproduce it with a unit test.

**Comment by tomasbjerre** [comment] 2018-09-26 12:06
tomas.bjerre85@gmail.com

**Comment by stoesselt** [comment] 2018-09-26 12:21
The url returns the changes for the first 6 changed files only. Changes of the ListView.cpp are not included. I will try to retrieve the information and I will have a look to the code you pointed out.

**Comment by tomasbjerre** [comment] 2018-09-26 12:31
Only first 6 changed files!? This code will assume all files are retrieved, unless more than 999999 changed files.

It happens here: https://github.com/tomasbjerre/violation-comments-to-bitbucket-server-lib/blob/master/src/main/java/se/bjurr/violations/comments/bitbucketserver/lib/client/BitbucketServerClient.java#L97

**Comment by stoesselt** [comment] 2018-09-26 12:57
Ok, so `rest/api/1.0/projects/P2/repos/code/pull-requests/48/changes?limit=999999` seems to report all files changed. At least ListView.cpp is included. 

However, your other request `rest/api/1.0/projects/P2/repos/code/pull-requests/48/diff?limit=999999` indeed only returns the changes for the first 6 files. As said before, many files were renamed and Bitbucket treat them as removed and added, so the whole content of many files has to be retrieved by this request. Without the content of `hunks` the json data looks like this:

```
{
	"fromHash":"9ab4dd79061abe6552bff5506505493e38d19e77",
	"toHash":"b7e95fdd339b9b8b98faa7a9a97b2600b761ecb6",
	"contextLines":10,
	"whitespace":"SHOW",
	"diffs":[
		{"source":
			{"components":["pump","build","Makefile.common.gcc.mk"],"parent":"pump/build","name":"Makefile.common.gcc.mk","extension":"mk","toString":"pump/build/Makefile.common.gcc.mk"
			},"destination":
			{"components":["pump","build","Makefile.common.gcc.mk"],"parent":"pump/build","name":"Makefile.common.gcc.mk","extension":"mk","toString":"pump/build/Makefile.common.gcc.mk"
			},"hunks":[]
		},
		{"source":
			{"components":["pump","build","Makefile.common.iar.mk"],"parent":"pump/build","name":"Makefile.common.iar.mk","extension":"mk","toString":"pump/build/Makefile.common.iar.mk"
			},"destination":
			{"components":["pump","build","Makefile.common.iar.mk"],"parent":"pump/build","name":"Makefile.common.iar.mk","extension":"mk","toString":"pump/build/Makefile.common.iar.mk"
			},"hunks":[]
		},
		{"source":
			{"components":["pump","build","controller","Makefile.gcc.mk"],"parent":"pump/build/controller","name":"Makefile.gcc.mk","extension":"mk","toString":"pump/build/controller/Makefile.gcc.mk"
			},"destination":
			{"components":["pump","build","controller","Makefile.gcc.mk"],"parent":"pump/build/controller","name":"Makefile.gcc.mk","extension":"mk","toString":"pump/build/controller/Makefile.gcc.mk"
			},"hunks":[]
		},
		{"source":
			{"components":["pump","build","controller","Makefile.iar.mk"],"parent":"pump/build/controller","name":"Makefile.iar.mk","extension":"mk","toString":"pump/build/controller/Makefile.iar.mk"
			},"destination":
			{"components":["pump","build","controller","Makefile.iar.mk"],"parent":"pump/build/controller","name":"Makefile.iar.mk","extension":"mk","toString":"pump/build/controller/Makefile.iar.mk"
			},"hunks":[]
		},
		{"source":
			{"components":["pump","build","eclipse","GccController",".cproject"],"parent":"pump/build/eclipse/GccController","name":".cproject","extension":"cproject","toString":"pump/build/eclipse/GccController/.cproject"
			},"destination":
			{"components":["pump","build","eclipse","GccController",".cproject"],"parent":"pump/build/eclipse/GccController","name":".cproject","extension":"cproject","toString":"pump/build/eclipse/GccController/.cproject"
			},"hunks":[]
		},
		{"source":
			{"components":["pump","build","eclipse","GccServiceProvider",".cproject"],"parent":"pump/build/eclipse/GccServiceProvider","name":".cproject","extension":"cproject","toString":"pump/build/eclipse/GccServiceProvider/.cproject"
			},"destination":
			{"components":["pump","build","eclipse","GccServiceProvider",".cproject"],"parent":"pump/build/eclipse/GccServiceProvider","name":".cproject","extension":"cproject","toString":"pump/build/eclipse/GccServiceProvider/.cproject"
			},"hunks":[]
		}],
	"truncated":true
}
```
So the `"truncated":true` clearly means that not everything is sent. The question is how to retrieve all data by incremental requests or how to get the changed lines in another way.

**Comment by tomasbjerre** [comment] 2018-09-26 13:41
Possible fix might be to use bitbucket-rest: https://github.com/cdancy/bitbucket-rest/issues/158

**Comment by tomasbjerre** [comment] 2018-09-26 14:51
@stoesselt Would you say this is a major issue? If it only happens for very big PR:s then maby it is just a minor.

**Comment by tomasbjerre** [comment] 2018-09-26 14:53
Perhaps an acceptable solution is to introduce logging when this happens, with a short explanation.

**Comment by stoesselt** [comment] 2018-09-26 15:19
I don't know what impact it has for the plugin when you declare this as a major. However, this issue makes me not to rely on the automatic comments anymore. I will check the Jenkins reports manually as workaround.

I doubt that this issue concerns only very big changes, but also medium changes. I mean, in my case I had hundreds of changed files. Nonetheless only 6 changed files were retrieved. Ok there were a lot of changes in these 6 files. But think of another case, where maybe the half of the change is retrieved and some comments are generated and the others not. I got distrustful because no comment at all was made. If some where added, I would believe the other files are ok, but oversee violations.

I followed your question on bitbucket-rest. It does not seem to be a solution. 
- Is there a way to retrieve the changed lines somehow else from Bitbucket? 
- Would it be an option to get the information from local git repository? I think this would break pull requests which cross repositories.

**Comment by tomasbjerre** [comment] 2018-09-26 15:45
It would be possible to get it from local repo, if it was always a merge commit to look at. But I think some people rebase source onto target or perhaps fast forward source to target... I think it may generate support issues.

I don't think you are using Maven or gradle, but I have made offline solutions for that:

* https://github.com/tomasbjerre/violations-maven-plugin
* https://github.com/tomasbjerre/violations-gradle-plugin

Perhaps a fix would be to change `http://localhost:7990/bitbucket/rest/api/1.0/projects/PROJECT_1/repos/violations-test/pull-requests/1/diff` to several requests, one per file, like:
`http://localhost:7990/bitbucket/rest/api/1.0/projects/PROJECT_1/repos/violations-test/pull-requests/1/diff/src/main/java/se/bjurr/violations/lib/example/MyClass.java`

If you do `rest/api/1.0/projects/P2/repos/code/pull-requests/48/diff/pump/source/gui/controls/ListView.cpp` you will probably not get a truncated response right?

**Comment by tomasbjerre** [comment] 2018-09-26 16:53
Releasing 1.90 now with a fix for this. Will now make rest calls for diff on each file.

Available in update center within a few hours.

Open issue again if not working!

**Closed by tomasbjerre** 2018-09-26 16:53 UTC
Labels: bug
